CKlab/urls.py
from django.contrib import admin
from django.urls import path, include

# 对于显示静态文件非常重要
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab/', include('lab.urls', namespace='lab')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab/urls.py
from django.urls import path
import lab.views as lv
app_name = 'lab'
urlpatterns = [
    # 首页
    path('', lv.lab, name='shuaxin'),
    # 内容页面
    path('content/', lv.content, name='content'),
    # 创客实验室
    path('CKlab/', lv.CKlab, name='CKlab'),
    # 师资力量
    path('teacher/', lv.teacher, name='teacher'),
    # 大数据
    path('BigData/', lv.BigData, name='BigData'),
    # 人工智能
    path('AI/', lv.AI, name='AI'),
    # 关于
    path('about/', lv.about, name='about'),
    # 联系我们
    path('contect/', lv.contect, name='contect'),


    # 活动相册
    path('album/', lv.album, name='album'),
    # 学生相册
    path('student/', lv.student, name='student'),

    # 通知公告
    path('notice/', lv.notice, name='notice'),
    path('noticeContent/<int:id>', lv.noticeContent, name='noticeContent'),
    # 讲座信息
    path('lecture/', lv.lecture, name='lecture'),
    path('lectureContent/<int:id>', lv.lectureContent, name='lectureContent'),
    # 娱乐活动
    path('fun/', lv.fun, name='fun'),
    path('funContent/<int:id>', lv.funContent, name='funContent'),
    # 历史竞赛
    path('competition/', lv.competition, name='competition'),
    path('competitionContent/<int:id>', lv.competitionContent, name='competitionContent'),
    # 项目课题
    path('project/', lv.project, name='project'),
    path('projectContent/<int:id>', lv.projectContent, name='projectContent'),
    # 学术成果
    path('essay/', lv.essay, name='essay'),
    path('essayContent/<int:id>', lv.essayContent, name='essayContent'),
    # 学术资料
    path('material/', lv.material, name='material'),
    path('materialContent/<int:id>', lv.materialContent, name='materialContent'),
]

lab/models.py
from django.db import models


# 相册表
class Album(models.Model):
    picture = models.ImageField(upload_to='album')
    information = models.TextField(max_length=100)

    def __str__(self):
        return self.information


# 学生表
class Student(models.Model):
    picture = models.ImageField(upload_to='student')
    name = models.TextField(max_length=20)

    def __str__(self):
        return self.name


# 通知公告表
class Notice(models.Model):
    title = models.CharField(max_length=200)
    content1 = models.TextField(max_length=2000, blank=True, null=True)
    content2 = models.TextField(max_length=2000, blank=True, null=True)
    content3 = models.TextField(max_length=2000, blank=True, null=True)
    file = models.FileField(upload_to='file', blank=True, null=True)
    time = models.DateField()

    def __str__(self):
        return self.title


# 讲座信息表
class Lecture(models.Model):
    title = models.CharField(max_length=200)
    people = models.CharField(max_length=100, blank=True, null=True)
    danwei = models.CharField(max_length=100, blank=True, null=True)
    lectureTime = models.CharField(max_length=100, blank=True, null=True)
    place = models.CharField(max_length=100, blank=True, null=True)
    content = models.TextField(max_length=2000)
    peopleIntroduce = models.TextField(max_length=2000, blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    time = models.DateField()

    def __str__(self):
        return self.title


# 娱乐活动表
class Fun(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=2000)
    time = models.DateField()

    def __str__(self):
        return self.title


# 历史竞赛表
class Competition(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=2000)
    file = models.FileField(upload_to='file', blank=True, null=True)
    time = models.DateField()

    def __str__(self):
        return self.title


# 项目课题表
class Project(models.Model):
    title = models.CharField(max_length=100)
    content1 = models.TextField(max_length=2000, blank=True, null=True)
    content2 = models.TextField(max_length=2000, blank=True, null=True)
    content3 = models.TextField(max_length=2000, blank=True, null=True)
    file = models.FileField(upload_to='file', blank=True, null=True)
    time = models.DateField()

    def __str__(self):
        return self.title


# 学术成果表
class Essay(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=2000)
    time = models.DateField()

    def __str__(self):
        return self.title


# 学术资料表
class Material(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=2000)
    time = models.DateField()

    def __str__(self):
        return self.title

lab/views.py
from django.shortcuts import render


# 主页
def lab(request):
    return render(request, 'index.html')


# 内嵌的html页面
def content(request):
    return render(request, 'html/content.html')


# 创客实验室
def CKlab(request):
    return render(request, 'html/CKlab.html')


# 师资力量
def teacher(request):
    return render(request, 'html/teacher.html')


# 大数据
def BigData(request):
    return render(request, 'html/BigData.html')


# 人工智能
def AI(request):
    return render(request, 'html/AI.html')


# 关于
def about(request):
    return render(request, 'html/about.html')


# 联系我们
def contect(request):
    return render(request, 'html/contect.html')

# 下面都是数据库
from . import models


# 活动相册
def album(request):
    img = models.Album.objects.all()
    return render(request, 'html/album.html', {'img': img})


# 学生相册
def student(request):
    img = models.Student.objects.all()
    return render(request, 'html/student.html', {'img': img})


# 通知公告（标题列表）
def notice(request):
    articals = models.Notice.objects.all().order_by('-time')
    return render(request, 'html/notice.html', {'articals': articals})


# 通知公告内容（内容）
def noticeContent(request, id):
    articles = models.Notice.objects.get(pk=id)
    return render(request, 'html/noticeContent.html', {'articles': articles})


# 讲座信息（标题列表）
def lecture(request):
    articals = models.Lecture.objects.all().order_by('-time')
    return render(request, 'html/lecture.html', {'articals': articals})


# 讲座信息内容（内容）
def lectureContent(request, id):
    articles = models.Lecture.objects.get(pk=id)
    return render(request, 'html/lectureContent.html', {'articles': articles})


# 娱乐活动（标题列表）
def fun(request):
    articals = models.Fun.objects.all().order_by('-time')
    return render(request, 'html/fun.html', {'articals': articals})


# 娱乐活动内容（内容）
def funContent(request, id):
    articles = models.Fun.objects.get(pk=id)
    return render(request, 'html/funContent.html', {'articles': articles})


# 历史竞赛（标题列表）
def competition(request):
    articals = models.Competition.objects.all().order_by('-time')
    return render(request, 'html/competition.html', {'articals': articals})


# 历史竞赛内容（内容）
def competitionContent(request, id):
    articles = models.Competition.objects.get(pk=id)
    return render(request, 'html/competitionContent.html', {'articles': articles})


# 项目课题（标题列表）
def project(request):
    articals = models.Project.objects.all().order_by('-time')
    return render(request, 'html/project.html', {'articals': articals})


# 项目课题内容（内容）
def projectContent(request, id):
    articles = models.Project.objects.get(pk=id)
    return render(request, 'html/projectContent.html', {'articles': articles})


# 学术成果（标题列表）
def essay(request):
    articals = models.Essay.objects.all().order_by('-time')
    return render(request, 'html/essay.html', {'articals': articals})


# 学术成果（内容）
def essayContent(request, id):
    articles = models.Essay.objects.get(pk=id)
    return render(request, 'html/essayContent.html', {'articles': articles})


# 学术资料（标题列表）
def material(request):
    articals = models.Material.objects.all().order_by('-time')
    return render(request, 'html/material.html', {'articals': articals})


# 学术资料（内容）
def materialContent(request, id):
    articles = models.Material.objects.get(pk=id)
    return render(request, 'html/materialContent.html', {'articles': articles})

templates/html/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>关于</title>
    <link rel="stylesheet" href="{% static '/css/basetype.css' %}">
</head>
<body>
<header>
    <h3>关于</h3>
    <hr>
</header>
<span class="text2">
    合肥工业创客实验室隶属于计算机与信息学院，她位于合肥工业大学翡翠湖校区科教大楼A座5楼。<br><br>
    我们长期欢迎对前后端感兴趣的本科、研究生同学们参与实验室网站的开发，共同建设实验室。<br><br>
    实验室倡导轻松、愉快、进步、个性发展的环境氛围，研究方向瞄准国际前沿，结合实验室成员自身喜好，
    充分调动师生的研究兴趣和工作热情，发挥团队的创新和协作能力，在传帮带的良好氛围里取得了丰硕的研究成果，
    是一个非常年轻有活力的团队。<br><br>
</span>
</body>
</html>

templates/html/competition.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>历史竞赛</title>
    <link rel="stylesheet" href="{% static '/css/text.css' %}">
</head>
<body>
<header>
    <h3>历史竞赛</h3>
    <hr>
</header>
<section>
    <ul>

        {% for artical in articals %}
            <li>
                <a href="{% url 'lab:competitionContent' artical.id %}">{{ artical.title }}</a>
                <span class="date">{{ artical.time }}</span>
            </li>
            <br>
        {% endfor %}



    </ul>
</section>
</body>
</html>

templates/html/competitionContent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>历史竞赛</title>
    <link rel="stylesheet" href="{% static '/css/text.css' %}">
</head>
<body>
<header>
    <h3>{{ articles.title }}</h3>
    <hr>
</header>
<section>
    <span>{{ articles.content }}</span><br><br><br><br>
</section>
<footer>
    <a href="/media/{{ articles.file }}">{{ articles.file }}</a>
</footer>

</body>
</html>

templates/html/content.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="{% static 'css/content.css' %}">
</head>
<body>
    <img src="{% static 'images/shouye.png' %}">
    <article>
        <span>
            合肥工业创客实验室隶属于计算机与信息学院，她位于合肥工业大学翡翠湖校区科教大楼A座5楼。<br>
            实验室倡导轻松、愉快、进步、个性发展的环境氛围，研究方向瞄准国际前沿，结合实验室成员自身喜好，
            充分调动师生的研究兴趣和工作热情，发挥团队的创新和协作能力，在传帮带的良好氛围里取得了丰硕的研究成果，
            是一个非常年轻有活力的团队。
        </span>
    </article>
</body>
</html>

templates/html/essay.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学术成果</title>
    <link rel="stylesheet" href="{% static '/css/text.css' %}">
</head>
<body>
<header>
    <h3>学术成果</h3>
    <hr>
</header>
<section>
    <ul>

        {% for artical in articals %}
            <li>
                <a href="{% url 'lab:essayContent' artical.id %}">{{ artical.title }}</a>
                <span class="date">{{ artical.time }}</span>
            </li>
            <br>
        {% endfor %}



    </ul>
</section>
</body>
</html>

templates/html/essayContent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学术成果</title>
    <link rel="stylesheet" href="{% static '/css/text.css' %}">
</head>
<body>
<header>
    <h3>学术成果</h3>
    <hr>
</header>
<section>
    <h3>{{ articles.title }}</h3>
    <span>{{ articles.content }}</span><br><br><br><br>

</section>
</body>
</html>

templates/html/fun.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>娱乐活动</title>
    <link rel="stylesheet" href="{% static '/css/text.css' %}">
</head>
<body>
<header>
    <h3>娱乐活动</h3>
    <hr>
</header>
<section>
    <ul>

        {% for artical in articals %}
            <li>
                <a href="{% url 'lab:funContent' artical.id %}">{{ artical.title }}</a>
                <span class="date">{{ artical.time }}</span>
            </li>
            <br>
        {% endfor %}



    </ul>
</section>
</body>
</html>

templates/html/funContent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>娱乐活动</title>
    <link rel="stylesheet" href="{% static '/css/text.css' %}">
</head>
<body>
<header>
    <h3>娱乐活动</h3>
    <hr>
</header>
<section>
    <h3>{{ articles.title }}</h3>
    <span>{{ articles.content }}</span>


</section>
</body>
</html>

templates/html/lecture.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>讲座信息</title>
    <link rel="stylesheet" href="{% static '/css/text.css' %}">
</head>
<body>
<header>
    <h3>讲座信息</h3>
    <hr>
</header>
<section>
    <ul>

        {% for artical in articals %}
            <li>
                <a href="{% url 'lab:lectureContent' artical.id %}">{{ artical.title }}</a>
                <span class="date">{{ artical.time }}</span>
            </li>
            <br>
        {% endfor %}



    </ul>
</section>
</body>
</html>

templates/html/material.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学术资料</title>
    <link rel="stylesheet" href="{% static '/css/text.css' %}">
</head>
<body>
<header>
    <h3>学术资料</h3>
    <hr>
</header>
<section>
    <ul>

        {% for artical in articals %}
            <li>
                <a href="{% url 'lab:materialContent' artical.id %}">{{ artical.title }}</a>
                <span class="date">{{ artical.time }}</span>
            </li>
            <br>
        {% endfor %}



    </ul>
</section>
</body>
</html>

templates/html/materialContent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学术资料</title>
    <link rel="stylesheet" href="{% static '/css/text.css' %}">
</head>
<body>
<header>
    <h3>学术资料：{{ articles.title }}</h3>
    <hr>
</header>
<section>
    <span>{{ articles.content }}</span><br><br>
    <span>{{ articles.url }}</span>
</section>
</body>
</html>

templates/html/notice.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>通知公告</title>
    <link rel="stylesheet" href="{% static '/css/text.css' %}">
</head>
<body>
<header>
    <h3>通知公告</h3>
    <hr>
</header>
<section>
    <ul>

        {% for artical in articals %}
            <li>
                <a href="{% url 'lab:noticeContent' artical.id %}">{{ artical.title }}</a>
                <span class="date">{{ artical.time }}</span>
            </li>
            <br>
        {% endfor %}



    </ul>
</section>
</body>
</html>

templates/html/projectContent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>项目课题</title>
    <link rel="stylesheet" href="{% static '/css/text.css' %}">
</head>
<body>
<header>
    <h3>项目课题：{{ articles.title }}</h3>
    <hr>
</header>
<section>
    <span>{{ articles.content1 }}</span><br><br>
    <span>{{ articles.content2 }}</span><br><br>
    <span>{{ articles.content3 }}</span><br><br><br><br>
    <a href="/media/{{ articles.file }}">{{ articles.file }}</a>
</section>
</body>
</html>

templates/html/teacher.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>师资力量</title>
    <link rel="stylesheet" href="{% static '/css/basetype.css' %}">
</head>
<body>
    <header>
        <h3>师资力量</h3>
        <hr>
    </header>
    <section>
        <img src="{% static '/images/teacher.jpg' %}">
        <article>
            <span class="text1">程文娟&nbsp;&nbsp;·&nbsp;&nbsp;教授</span>
            <br>
            <span class="text1">基本信息</span>
            <span class="text2">
                1970年12月生，安徽怀宁人，教授，硕士生导师，博士。<br>
                1993年起至今，合肥工业大学计算机与信息学院从事教学科研工作；
                近年来主持国家自然科学基金项目1项，
                教育部研究项目1项、安徽省自然科学基金1项、安徽省科技厅年度重点科研项目1项、
                安徽省高等学校自然科学研究重点项目1项，参加国家自然科学基金3项和省部级多项研究工作，
                先后获得安徽省科学技术奖励2项、安徽省科技进步奖1项、合肥市科技进步二等奖1项，
                安徽省教学成果奖一等奖和其它各种教学成果奖5项，主编安徽省“十一五”规划教材1部、
                作为主要成员参加两门国家级精品课程和两门省级精品课程的建设工作，出版专著和教材7部，
                发表论文30余篇。
            </span>
            <span class="text1">研究方向</span>
            <span class="text2">
                计算机应用技术、模式识别、智能计算与传感器技术等<br>
                主持及参加完成多项省部级研究项目，目前主持在研国家自然科学基金项目。<br>
                欢迎各相关专业的学生联系报考硕士研究生。
            </span>
            <span class="text1">获奖情况</span>
            <span class="text2">
                1996年获安徽省科技进步四等奖<br>
                2002年获安徽省科学技术奖三等奖<br>
                2008年获安徽省高等学校省级教学成果一等奖<br>
                2010年获安徽省科学技术奖三等奖一项<br>
                2013年获安徽省高等学校省级教学成果特等奖<br>
                2014年获合肥市科技进步二等奖1项<br>
                获国家发明专利2项，受理发明专利2项
            </span>
            <span class="text1">主要论著</span>
            <span class="text2">
                《计算机应用技术》<br>
                《大学计算机》<br>
                《计算机组装与维护》<br>
                《图像处理Photoshop教程》<br>
                安徽省“十一五”规划教材《嵌入式实时操作系统μC/OSⅡ教程》等
            </span>
            <span class="text1">教学工作</span>
            <span class="text2">
                程序设计基础<br>
                程序语言( C++)<br>
                图像处理软件应用<br>
            </span>
        </article>
    </section>
</body>
</html>

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- 响应式设计 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>创客实验室</title>
    <!-- 引入 Bootstrap 所需文件 -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://code.jquery.com/jquery.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- 引入自己编写的样式文件 -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>

<body>
    <header>
            <img src="{% static 'images/top.png' %}">
    </header>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- 适应手机，手机上的导航栏右边会有个下拉列表 -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- 导航栏 -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'lab:shuaxin' %}">首页<span class="sr-only">(current)</span></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">实验室介绍<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'lab:CKlab' %}" target="content">创客实验室</a></li>
                            <li><a href="{% url 'lab:teacher' %}" target="content">师资力量</a></li>
                            <li><a href="{% url 'lab:student' %}" target="content">实验室成员</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">研究方向<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'lab:BigData' %}" target="content">大数据</a></li>
                            <li><a href="{% url 'lab:AI' %}" target="content">人工智能</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="{% url 'lab:notice' %}" target="content">通知公告</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">大学生创新研究<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'lab:project' %}" target="content">项目课题</a></li>
                            <li><a href="{% url 'lab:competition' %}" target="content">历史竞赛</a></li>
                            <li><a href="{% url 'lab:lecture' %}" target="content">讲座信息</a></li>
                            <li><a href="{% url 'lab:material' %}" target="content">学术资料</a></li>
                            <li><a href="{% url 'lab:essay' %}" target="content">学术成果</a></li>
                            <li><a href="{% url 'lab:fun' %}" target="content">娱乐活动</a></li>
                            <li><a href="#">其它信息</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'lab:album' %}" target="content">相册</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'lab:about' %}" target="content">关于</a></li>
                    <li><a href="{% url 'lab:contect' %}" target="content">联系我们</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- 内嵌页面，导航栏链接的内容将在此展示 -->
    <iframe name="content" src="{% url 'lab:content' %}" scrolling="auto"></iframe>
    <!-- 页脚：版权、设计者 -->
    <footer>
        <div>
            <span>友情链接：&nbsp;&nbsp;</span>
            <a href="http://www.hfut.edu.cn/">合肥工业大学</a>&nbsp;&nbsp;
            <a href="http://ci.hfut.edu.cn/main.htm">计算机与信息学院</a>&nbsp;&nbsp;
            <a href="http://my.hfut.edu.cn/">数字化信息门户</a>
        </div>
        <div>
            <span>© 2018 合肥工业大学创客实验室 , All Rights Reserved.</span><br>
            <span>Designed by MaYu</span>
        </div>
    </footer>
</body>
</html>